/* Generated By:JavaCC: Do not edit this line. ComportementRobotsConstants.java */
package Parsing;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ComportementRobotsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STAR = 5;
  /** RegularExpression Id. */
  int AO = 6;
  /** RegularExpression Id. */
  int AF = 7;
  /** RegularExpression Id. */
  int PV = 8;
  /** RegularExpression Id. */
  int OU = 9;
  /** RegularExpression Id. */
  int DP = 10;
  /** RegularExpression Id. */
  int PREF = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"*\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"|\"",
    "\":\"",
    "\">\"",
    "\"H\"",
    "\"K\"",
    "\"O\"",
    "\"J\"",
    "\"P\"",
  };

}
